from sqlalchemy import Column, Integer, Float, String, DateTime
from datetime import datetime, timezone

from app.core.database import Base


class TelemetryLegacy(Base):
    """
    Legacy telemetry data table.

    Stores CSV data generated by the legacy CLI service.
    Replaces the Pascal-based telemetry generator.
    """
    __tablename__ = "telemetry_legacy"

    id = Column(Integer, primary_key=True, autoincrement=True)
    recorded_at = Column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Time when telemetry was recorded"
    )
    voltage = Column(Float, nullable=False, comment="Voltage reading")
    temp = Column(Float, nullable=False, comment="Temperature reading")
    source_file = Column(
        String(255),
        nullable=True,
        comment="Source CSV file name"
    )

    def __repr__(self) -> str:
        return f"<TelemetryLegacy(id={self.id}, recorded_at={self.recorded_at}, voltage={self.voltage}, temp={self.temp})>"
